/**
 * @file qmi_includes.h
 *
 * Auto-generated QMI meta include file.
 *
 * @warning Do not edit this file manually, it is auto-generated by create.sh on firmware release.
 *
 * Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
 */

#ifndef LEGATO_QMI_INCLUDE_GUARD
#define LEGATO_QMI_INCLUDE_GUARD

// Framework
#include "qmi_client.h"
#include "qmi_idl_lib.h"
#include "qmi_idl_lib_internal.h"
#include "qmi_port_defs.h"
#include "qmi_client_instance_defs.h"
#include "common_v01.h"

// Services
#include "application_traffic_pairing_v01.h"
#include "bsp_service_type_messages_v01.h"
#include "card_application_toolkit_v02.h"
#include "circuit_switched_video_telephony_v01.h"
#include "coexistence_manager_v01.h"
#include "control_service_v01.h"
#include "data_common_v01.h"
#include "data_filter_service_v01.h"
#include "data_port_mapper_v01.h"
#include "data_system_determination_v01.h"
#include "device_management_service_v01.h"
#include "ip_multimedia_subsystem_application_v01.h"
#include "ip_multimedia_subsystem_dcm_v01.h"
#include "ip_multimedia_subsystem_presence_v01.h"
#include "ip_multimedia_subsystem_rtp_v01.h"
#include "ip_multimedia_subsystem_settings_v01.h"
#include "ip_multimedia_subsystem_video_telephony_v01.h"
#include "location_service_v02.h"
#include "lowi_service_v01.h"
#include "network_access_service_common_v01.h"
#include "network_access_service_v01.h"
#include "persistent_device_configuration_v01.h"
#include "phonebook_manager_service_v01.h"
#include "qapi_apss_0_v01.h"
#include "qapi_common_v01.h"
#include "qapi_loc_v01.h"
#include "qapi_m2m_general_v01.h"
#include "qapi_mpss_0_v01.h"
#include "qapi_sfs_v01.h"
#include "qapi_swi_common_v01.h"
#include "qmi_adc_service_v01.h"
#include "qmi_ims_vt_v01.h"
#include "qmi_platform.h"
#include "qti_wlan_scm_msgr_v01.h"
#include "qualcomm_mobile_access_point_v01.h"
#include "radio_frequency_radiated_performance_enhancement_v01.h"
#include "sar_vs_service_v01.h"
#include "specific_absorption_rate_v01.h"
#include "swiqmi_audio_v01.h"
#include "user_identity_module_remote_v01.h"
#include "user_identity_module_v01.h"
#include "voice_service_common_v02.h"
#include "voice_service_v01.h"
#include "voice_service_v02.h"
#include "wireless_data_administrative_service_v01.h"
#include "wireless_data_service_common_v01.h"
#include "wireless_data_service_v01.h"
#include "wireless_messaging_service_v01.h"

#endif /* LEGATO_QMI_INCLUDE_GUARD */

